openapi: 3.1.0
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    termsOfService: http://charlotte.io/termsOfService

    version: 1.0.409

servers:
    - url: http://localhost:3001/api/v2

tags:
    - name: Bank Accounts
      description: Access to bank accounts

    - name: Transactions
      description: Access to transactions

paths:
    /bankAccounts/{bankAccountId}/transactions:
        get:
            tags: [Transactions]
            summary: Transaction  from the specified bank account
            parameters:
                - name: bankAccountId
                  in: path
                  description: ID of the specified bank account
                  required: true
                  schema:
                      type: string

                - name: page
                  description: Example:1
                  in: query
                  required: true
                  schema:
                      type: integer
                      minimum: 1

                - name: pageSize
                  description: number of transactions per page Example:10
                  in: query
                  required: true
                  schema:
                      type: integer
                      minimum: 1
                      maximum: 10
            responses:
                "400":
                    description: Invalid Fields
                "401":
                    $ref: "#/components/responses/UnauthorizedError"
                "404":
                    description: Not found
                "500":
                    description: Internal Server Error
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: string
                                        date:
                                            type: string
                                        description:
                                            type: string
                                        currency:
                                            type: string
                                            enum: [$, €]
                                        amount:
                                            type: number

    /bankAccounts/{bankAccountId}/transactions/{transactionId}:
        get:
            tags: [Transactions]
            summary: Details of each transaction
            parameters:
                - name: bankAccountId
                  in: path
                  description: ID of the specified bank account
                  required: true
                  schema:
                      type: string

                - name: transactionId
                  in: path
                  description: ID of the specified transaction
                  required: true
                  schema:
                      type: string
            responses:
                "400":
                    description: Invalid Fields
                "401":
                    $ref: "#/components/responses/UnauthorizedError"
                "500":
                    description: Internal Server Error
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    TransactionType:
                                        type: string
                                        enum: [Electronic, card]
                                    Category:
                                        type: string
                                        enum: [Food, clothes, restaurant]
                                    Note:
                                        type: string

        patch:
            tags: [Transactions]
            summary: Update of the specified transaction
            requestBody:
                description: Update one or more fields of a transaction
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                TransactionType:
                                    type: string
                                    enum: [Electronic, card]
                                Category:
                                    type: string
                                    enum: [Food, clothes, restaurant]
                                Note:
                                    type: string
            responses:
                "400":
                    description: Bad request
                "401":
                    $ref: "#/components/responses/UnauthorizedError"
                "422":
                    description: Unprocessable Entity
                "500":
                    description: Internal Server Error
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    TransactionType:
                                        type: string
                                        enum: [Electronic, card]
                                    Category:
                                        type: string
                                        enum: [Food, clothes, restaurant]
                                    Note:
                                        type: string
    /bankAccounts:
        get:
            tags:
                - Bank Accounts
            summary: BankAccounst API
            parameters:
                - name: page
                  description: Example:1
                  in: query
                  required: true
                  schema:
                      type: integer
                      minimum: 1

                - name: pageSize
                  description: number of bankAccount per page Example:3
                  in: query
                  required: true
                  schema:
                      type: integer
                      minimum: 1
                      maximum: 10

            responses:
                "400":
                    description: Invalid Fields
                "401":
                    $ref: "#/components/responses/UnauthorizedError"
                "404":
                    description: Not found
                "500":
                    description: Internal Server Error
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        type:
                                            type: string
                                            enum: [credit-card, checking, savings]
                                        accountId:
                                            type: string
                                        currency:
                                            type: string
                                            enum: [$, €]
                                        userId:
                                            type: string
                                        balanceType:
                                            type: string
